name: Setup Dependencies
description: Install system dependencies, Go, Helm, and Docker (shared across tests)

inputs:
  protocol:
    description: 'Protocol to test (nfs, nvmeof, or both)'
    required: true
  go-version:
    description: 'Go version to use'
    required: false
    default: '1.25.4'

runs:
  using: composite
  steps:
    - name: Install system dependencies
      shell: bash
      env:
        INPUT_PROTOCOL: ${{ inputs.protocol }}
      run: |
        # Check if packages are already installed to avoid unnecessary apt-get update
        NEED_UPDATE=false
        
        if ! command -v jq &> /dev/null; then
          NEED_UPDATE=true
        fi
        
        if [[ "$INPUT_PROTOCOL" == "nfs" ]] || [[ "$INPUT_PROTOCOL" == "both" ]]; then
          if ! dpkg -l | grep -q nfs-common; then
            NEED_UPDATE=true
          fi
        fi
        
        if [[ "$INPUT_PROTOCOL" == "nvmeof" ]] || [[ "$INPUT_PROTOCOL" == "both" ]]; then
          if ! command -v nvme &> /dev/null; then
            NEED_UPDATE=true
          fi
        fi
        
        if [ "$NEED_UPDATE" = true ]; then
          echo "Installing missing packages..."
          sudo apt-get update
          sudo apt-get install -y curl wget git make jq
          
          if [[ "$INPUT_PROTOCOL" == "nfs" ]] || [[ "$INPUT_PROTOCOL" == "both" ]]; then
            sudo apt-get install -y nfs-common
          fi
          
          if [[ "$INPUT_PROTOCOL" == "nvmeof" ]] || [[ "$INPUT_PROTOCOL" == "both" ]]; then
            sudo apt-get install -y nvme-cli
            sudo modprobe nvme-tcp || echo "nvme-tcp module already loaded"
          fi
        else
          echo "All required packages already installed, skipping apt-get update"
        fi

    - name: Install Docker
      shell: bash
      run: |
        if ! command -v docker &> /dev/null; then
          echo "Installing Docker..."
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          rm get-docker.sh
        else
          echo "Docker already installed"
        fi
        sudo usermod -aG docker $USER

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ inputs.go-version }}
        cache: false

    - name: Install Helm
      shell: bash
      run: |
        if ! command -v helm &> /dev/null; then
          echo "Installing Helm..."
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
        else
          echo "Helm already installed"
        fi

    - name: Verify CSI driver image availability
      shell: bash
      run: |
        # Verify that the CSI driver image is available from registries
        # We don't pre-pull or sideload - let k3s pull directly from the registry
        echo "Verifying CSI driver image is available from registry..."
        echo "Image will be pulled from bfenski/tns-csi:latest or ghcr.io/fenio/tns-csi:latest"
        echo "No pre-pull or sideloading - k3s will pull directly from registry with imagePullPolicy: Always"
