name: Setup Dependencies
description: Install system dependencies, Go, Helm, and Docker (shared across tests)

inputs:
  protocol:
    description: 'Protocol to test (nfs, nvmeof, or both)'
    required: true
  go-version:
    description: 'Go version to use'
    required: false
    default: '1.25.4'

runs:
  using: composite
  steps:
    - name: Install system dependencies
      shell: bash
      env:
        INPUT_PROTOCOL: ${{ inputs.protocol }}
      run: |
        echo "=== Installing system dependencies on pristine VM ==="
        sudo apt-get update
        sudo apt-get install -y curl wget git make jq
        
        if [[ "$INPUT_PROTOCOL" == "nfs" ]] || [[ "$INPUT_PROTOCOL" == "both" ]]; then
          sudo apt-get install -y nfs-common
        fi
        
        if [[ "$INPUT_PROTOCOL" == "nvmeof" ]] || [[ "$INPUT_PROTOCOL" == "both" ]]; then
          sudo apt-get install -y nvme-cli
          
          # Install linux-modules-extra for nvme-tcp kernel module
          KERNEL_VERSION=$(uname -r)
          echo "Installing linux-modules-extra for kernel ${KERNEL_VERSION}"
          sudo apt-get install -y linux-modules-extra-${KERNEL_VERSION} || echo "linux-modules-extra not available, trying to load module anyway"
          
          # Load nvme-tcp kernel module (required for NVMe-oF)
          sudo modprobe nvme-tcp || {
            echo "ERROR: Failed to load nvme-tcp kernel module"
            echo "NVMe-oF tests will fail without this module"
            exit 1
          }
          echo "nvme-tcp kernel module loaded successfully"
        fi

    - name: Install Docker
      shell: bash
      run: |
        echo "=== Installing Docker ==="
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh
        rm get-docker.sh
        sudo usermod -aG docker $USER

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ inputs.go-version }}
        cache: false

    - name: Install Helm
      shell: bash
      run: |
        echo "=== Installing Helm ==="
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Ready for testing
      shell: bash
      run: |
        echo "=== Dependencies installed, ready for testing ==="
