name: Setup Dependencies
description: Install system dependencies, Go, Helm, and Docker (shared across tests)

inputs:
  protocol:
    description: 'Protocol to test (nfs, nvmeof, or both)'
    required: true
  go-version:
    description: 'Go version to use'
    required: false
    default: '1.25.3'

runs:
  using: composite
  steps:
    - name: Install system dependencies
      shell: bash
      run: |
        # Check if packages are already installed to avoid unnecessary apt-get update
        NEED_UPDATE=false
        
        if ! command -v jq &> /dev/null; then
          NEED_UPDATE=true
        fi
        
        if [[ "${{ inputs.protocol }}" == "nfs" ]] || [[ "${{ inputs.protocol }}" == "both" ]]; then
          if ! dpkg -l | grep -q nfs-common; then
            NEED_UPDATE=true
          fi
        fi
        
        if [[ "${{ inputs.protocol }}" == "nvmeof" ]] || [[ "${{ inputs.protocol }}" == "both" ]]; then
          if ! command -v nvme &> /dev/null; then
            NEED_UPDATE=true
          fi
        fi
        
        if [ "$NEED_UPDATE" = true ]; then
          echo "Installing missing packages..."
          sudo apt-get update
          sudo apt-get install -y curl wget git make jq
          
          if [[ "${{ inputs.protocol }}" == "nfs" ]] || [[ "${{ inputs.protocol }}" == "both" ]]; then
            sudo apt-get install -y nfs-common
          fi
          
          if [[ "${{ inputs.protocol }}" == "nvmeof" ]] || [[ "${{ inputs.protocol }}" == "both" ]]; then
            sudo apt-get install -y nvme-cli
            sudo modprobe nvme-tcp || echo "nvme-tcp module already loaded"
          fi
        else
          echo "All required packages already installed, skipping apt-get update"
        fi

    - name: Install Docker and upgrade containerd
      shell: bash
      run: |
        if ! command -v docker &> /dev/null; then
          echo "Installing Docker..."
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          rm get-docker.sh
        else
          echo "Docker already installed"
        fi
        
        # Upgrade containerd to 2.x to be compatible with k3s/k0s
        # k3s ships with containerd 2.x (v3 shims), but Docker installs containerd 1.x (v2 shims)
        # This causes "unsupported shim version (3)" errors when running k3s then minikube
        echo "Upgrading containerd to 2.x for compatibility..."
        CONTAINERD_VERSION=$(containerd --version 2>/dev/null | awk '{print $3}' | sed 's/^v//' | cut -d. -f1 || echo "0")
        if [ "$CONTAINERD_VERSION" -lt 2 ]; then
          echo "Current containerd version is 1.x, upgrading to 2.x..."
          sudo systemctl stop docker
          sudo systemctl stop containerd || true
          
          # Install containerd 2.x from official releases
          CONTAINERD_VERSION="2.0.0"
          wget -q https://github.com/containerd/containerd/releases/download/v${CONTAINERD_VERSION}/containerd-${CONTAINERD_VERSION}-linux-amd64.tar.gz
          sudo tar Cxzf /usr containerd-${CONTAINERD_VERSION}-linux-amd64.tar.gz
          rm containerd-${CONTAINERD_VERSION}-linux-amd64.tar.gz
          
          sudo systemctl start containerd
          sudo systemctl start docker
          echo "Upgraded to containerd $(containerd --version)"
        else
          echo "containerd is already 2.x: $(containerd --version)"
        fi
        
        # Add user to docker group if USER is set (not in Docker-based runners)
        if [ -n "$USER" ]; then
          sudo usermod -aG docker $USER || true
        fi

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ inputs.go-version }}
        cache: false

    - name: Install kubectl
      shell: bash
      run: |
        if ! command -v kubectl &> /dev/null; then
          echo "Installing kubectl..."
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          rm kubectl
        else
          echo "kubectl already installed"
        fi

    - name: Install Helm
      shell: bash
      run: |
        if ! command -v helm &> /dev/null; then
          echo "Installing Helm..."
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
        else
          echo "Helm already installed"
        fi

    - name: Build CSI driver image
      shell: bash
      run: |
        # On self-hosted runner, skip rebuild if image already exists
        if sudo docker inspect bfenski/tns-csi:latest &>/dev/null; then
          echo "CSI driver image already exists, skipping build"
          sudo docker images | grep bfenski/tns-csi || true
        else
          echo "Building CSI driver image..."
          sudo -E make docker-build
        fi
