name: Setup Fresh minikube Cluster
description: Destroy existing minikube cluster and create a fresh one for testing

runs:
  using: composite
  steps:
    - name: Destroy all existing Kubernetes clusters
      shell: bash
      run: |
        echo "=== Destroying ALL existing Kubernetes clusters for clean state ==="
        
        # Stop k3s if running
        if command -v k3s-uninstall.sh &> /dev/null; then
          echo "Uninstalling k3s..."
          sudo k3s-uninstall.sh || true
        fi
        sudo rm -rf /etc/rancher/k3s /var/lib/rancher/k3s || true
        
        # Stop k0s if running
        if command -v k0s &> /dev/null; then
          echo "Stopping k0s..."
          sudo k0s stop || true
          sudo k0s reset || true
        fi
        sudo systemctl stop k0scontroller.service || true
        sudo systemctl stop k0sworker.service || true
        sudo systemctl disable k0scontroller.service || true
        sudo systemctl disable k0sworker.service || true
        sudo rm -rf /etc/k0s /var/lib/k0s || true
        
        # Clean up k0s containerd processes and sockets
        echo "Cleaning up containerd from k0s..."
        sudo pkill -9 containerd || true
        sudo pkill -9 containerd-shim || true
        sudo rm -rf /run/containerd/containerd.sock || true
        sudo rm -rf /run/k0s/containerd.sock || true
        sudo rm -rf /var/lib/k0s/containerd || true
        
        # Restart Docker daemon to restore clean containerd state
        echo "Restarting Docker daemon..."
        sudo systemctl restart docker || true
        sleep 5
        
        # Wait for Docker to be ready
        echo "Waiting for Docker to be ready..."
        for i in {1..30}; do
          if docker ps &>/dev/null; then
            echo "Docker is ready"
            break
          fi
          echo "Docker not ready yet, waiting... (attempt $i/30)"
          sleep 2
        done
        
        # Stop minikube if running
        if command -v minikube &> /dev/null; then
          echo "Stopping minikube..."
          minikube delete --all --purge || true
        fi
        sudo rm -rf ~/.minikube || true
        
        # Clean up kubeconfig
        sudo rm -rf ~/.kube/config || true
        
        # Wait for port 6443 to be free
        echo "Waiting for port 6443 to be free..."
        for i in {1..30}; do
          if ! sudo lsof -i :6443 &>/dev/null; then
            echo "Port 6443 is free"
            break
          fi
          echo "Port 6443 still in use, waiting... (attempt $i/30)"
          sleep 2
        done
        
        # Kill any remaining processes on port 6443
        sudo lsof -ti :6443 | xargs -r sudo kill -9 || true
        sleep 2
        
        echo "All clusters destroyed"

    - name: Install/Update minikube
      shell: bash
      run: |
        echo "=== Ensuring minikube is installed ==="
        if ! command -v minikube &> /dev/null; then
          echo "Installing minikube..."
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          rm minikube-linux-amd64
        else
          echo "minikube already installed: $(minikube version)"
        fi

    - name: Start minikube cluster
      shell: bash
      run: |
        echo "=== Starting fresh minikube cluster ==="
        
        # Start minikube with Docker driver (most compatible with self-hosted runners)
        # Use none driver if running as root, otherwise use docker
        if [[ $EUID -eq 0 ]]; then
          DRIVER="none"
        else
          DRIVER="docker"
        fi
        
        echo "Using driver: ${DRIVER}"
        
        minikube start \
          --driver="${DRIVER}" \
          --container-runtime=containerd \
          --wait=all \
          --wait-timeout=5m
        
        echo "=== Cluster nodes ==="
        kubectl get nodes
        echo "=== Cluster version ==="
        kubectl version

    - name: Import CSI driver image to minikube
      shell: bash
      run: |
        echo "=== Importing CSI driver image to minikube ==="
        # minikube can load images from Docker
        minikube image load bfenski/tns-csi:latest
        
        # Verify image is available
        echo "Verifying image in minikube..."
        minikube ssh -- crictl images | grep tns-csi || {
          echo "WARNING: Image may not be loaded, attempting alternative method..."
          # Alternative: save and load directly
          docker save bfenski/tns-csi:latest | minikube ssh -- docker load
        }
