name: Setup Snapshot Support
description: Install Kubernetes Volume Snapshot CRDs and Controller

runs:
  using: composite
  steps:
    - name: Install Snapshot CRDs
      shell: bash
      run: |
        echo "=== Installing Volume Snapshot CRDs ==="
        kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-8.2/client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
        kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-8.2/client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
        kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-8.2/client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml
        echo "Waiting for CRDs to be established..."
        kubectl wait --for condition=established --timeout=60s crd/volumesnapshotclasses.snapshot.storage.k8s.io
        kubectl wait --for condition=established --timeout=60s crd/volumesnapshotcontents.snapshot.storage.k8s.io
        kubectl wait --for condition=established --timeout=60s crd/volumesnapshots.snapshot.storage.k8s.io
    
    - name: Install Snapshot Controller
      shell: bash
      run: |
        echo "=== Installing Snapshot Controller ==="
        kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-8.2/deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml
        kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-8.2/deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
        echo "Waiting for snapshot-controller to be ready..."
        kubectl wait --for=condition=available --timeout=60s deployment/snapshot-controller -n kube-system || true
        kubectl get pods -n kube-system | grep snapshot-controller
