name: Setup k3s Cluster
description: Install k3s cluster on pristine VM runner

inputs:
  truenas_host:
    description: 'TrueNAS host'
    required: false
  truenas_api_key:
    description: 'TrueNAS API key'
    required: false
  truenas_pool:
    description: 'TrueNAS pool'
    required: false

runs:
  using: composite
  steps:
    - name: Install k3s
      shell: bash
      run: |
        echo "=== Installing k3s cluster on pristine VM ==="
        curl -sfL https://get.k3s.io | sh -s - \
          --write-kubeconfig-mode 644 \
          --disable traefik \
          --disable servicelb
        
        echo "Waiting for k3s service to start..."
        sleep 15
        
        echo "Waiting for cluster to become ready..."
        retries=0
        while [[ $retries -lt 24 ]]; do
          if sudo k3s kubectl get nodes &>/dev/null; then
            if sudo k3s kubectl wait --for=condition=Ready node --all --timeout=10s 2>/dev/null; then
              echo "k3s cluster ready"
              sudo k3s kubectl get nodes
              exit 0
            fi
          fi
          echo "Waiting for cluster... (attempt $((retries+1))/24)"
          sleep 5
          retries=$((retries + 1))
        done
        echo "ERROR: Cluster failed to become ready within 2 minutes"
        sudo systemctl status k3s || true
        exit 1

    - name: Configure kubectl
      shell: bash
      run: |
        mkdir -p ~/.kube
        sudo cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
        sudo chown $USER:$USER ~/.kube/config
        echo "=== Cluster nodes ==="
        kubectl get nodes
        echo "=== Cluster version ==="
        kubectl version

    - name: Verify cluster
      shell: bash
      run: |
        echo "=== k3s cluster ready ==="
        kubectl get nodes
