name: Setup Fresh k3s Cluster
description: Destroy existing k3s cluster and create a fresh one for testing

runs:
  using: composite
  steps:
    - name: Destroy existing k3s cluster
      shell: bash
      run: |
        echo "=== Destroying existing k3s cluster for clean state ==="
        if command -v k3s-uninstall.sh &> /dev/null; then
          sudo k3s-uninstall.sh || true
        fi
        sudo rm -rf /etc/rancher/k3s /var/lib/rancher/k3s ~/.kube/config || true
        echo "k3s cluster destroyed"

    - name: Install k3s (fresh cluster)
      shell: bash
      run: |
        echo "=== Installing fresh k3s cluster ==="
        curl -sfL https://get.k3s.io | sh -s - \
          --write-kubeconfig-mode 644 \
          --disable traefik \
          --disable servicelb
        
        echo "Waiting for k3s service to start..."
        sleep 15
        
        echo "Waiting for cluster nodes to register and become ready..."
        retries=0
        while [[ $retries -lt 24 ]]; do
          if sudo k3s kubectl get nodes &>/dev/null; then
            echo "Node registered, checking Ready condition..."
            if sudo k3s kubectl wait --for=condition=Ready node --all --timeout=10s 2>/dev/null; then
              echo "Fresh k3s cluster ready"
              sudo k3s kubectl get nodes
              exit 0
            fi
          fi
          echo "Waiting for cluster... (attempt $((retries+1))/24)"
          sleep 5
          retries=$((retries + 1))
        done
        echo "ERROR: Cluster failed to become ready within 2 minutes"
        sudo systemctl status k3s || true
        exit 1

    - name: Configure kubectl
      shell: bash
      run: |
        mkdir -p ~/.kube
        sudo cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
        sudo chown $USER:$USER ~/.kube/config
        echo "=== Cluster nodes ==="
        kubectl get nodes
        echo "=== Cluster version ==="
        kubectl version

    - name: Import CSI driver image to k3s
      shell: bash
      run: |
        echo "=== Importing CSI driver image to k3s ==="
        sudo docker save bfenski/tns-csi:latest | sudo k3s ctr images import -
