name: Setup Fresh k3s Cluster
description: Destroy existing k3s cluster and create a fresh one for testing

runs:
  using: composite
  steps:
    - name: Destroy all existing Kubernetes clusters
      shell: bash
      run: |
        echo "=== Destroying ALL existing Kubernetes clusters for clean state ==="
        
        # Stop k3s if running
        if command -v k3s-uninstall.sh &> /dev/null; then
          echo "Uninstalling k3s..."
          sudo k3s-uninstall.sh || true
        fi
        sudo rm -rf /etc/rancher/k3s /var/lib/rancher/k3s || true
        
        # Stop k0s if running
        if command -v k0s &> /dev/null; then
          echo "Stopping k0s..."
          sudo k0s stop || true
          sudo k0s reset || true
        fi
        sudo systemctl stop k0scontroller.service || true
        sudo systemctl stop k0sworker.service || true
        sudo systemctl disable k0scontroller.service || true
        sudo systemctl disable k0sworker.service || true
        sudo rm -rf /etc/k0s /var/lib/k0s || true
        
        # Stop minikube if running
        if command -v minikube &> /dev/null; then
          echo "Stopping minikube..."
          minikube delete || true
        fi
        
        # Clean up kubeconfig
        sudo rm -rf ~/.kube/config || true
        
        # Wait for port 6443 to be free
        echo "Waiting for port 6443 to be free..."
        for i in {1..30}; do
          if ! sudo lsof -i :6443 &>/dev/null; then
            echo "Port 6443 is free"
            break
          fi
          echo "Port 6443 still in use, waiting... (attempt $i/30)"
          sleep 2
        done
        
        # Kill any remaining processes on port 6443
        sudo lsof -ti :6443 | xargs -r sudo kill -9 || true
        sleep 2
        
        echo "All clusters destroyed"

    - name: Install k3s (fresh cluster)
      shell: bash
      run: |
        echo "=== Installing fresh k3s cluster ==="
        curl -sfL https://get.k3s.io | sh -s - \
          --write-kubeconfig-mode 644 \
          --disable traefik \
          --disable servicelb
        
        echo "Waiting for k3s service to start..."
        sleep 15
        
        echo "Waiting for cluster nodes to register and become ready..."
        retries=0
        while [[ $retries -lt 24 ]]; do
          if sudo k3s kubectl get nodes &>/dev/null; then
            echo "Node registered, checking Ready condition..."
            if sudo k3s kubectl wait --for=condition=Ready node --all --timeout=10s 2>/dev/null; then
              echo "Fresh k3s cluster ready"
              sudo k3s kubectl get nodes
              exit 0
            fi
          fi
          echo "Waiting for cluster... (attempt $((retries+1))/24)"
          sleep 5
          retries=$((retries + 1))
        done
        echo "ERROR: Cluster failed to become ready within 2 minutes"
        sudo systemctl status k3s || true
        exit 1

    - name: Configure kubectl
      shell: bash
      run: |
        mkdir -p ~/.kube
        sudo cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
        sudo chown $USER:$USER ~/.kube/config
        echo "=== Cluster nodes ==="
        kubectl get nodes
        echo "=== Cluster version ==="
        kubectl version

    - name: Import CSI driver image to k3s
      shell: bash
      run: |
        echo "=== Importing CSI driver image to k3s ==="
        sudo docker save bfenski/tns-csi:latest | sudo k3s ctr images import -
