name: Setup k3s Cluster
description: Install k3s cluster on pristine VM runner

inputs:
  truenas_host:
    description: 'TrueNAS host'
    required: false
  truenas_api_key:
    description: 'TrueNAS API key'
    required: false
  truenas_pool:
    description: 'TrueNAS pool'
    required: false

runs:
  using: composite
  steps:
    - name: Tune OS for Kubernetes
      shell: bash
      run: |
        echo "=== Tuning OS network settings for concurrent connections ==="
        
        # Increase TCP connection backlog for API server
        sudo sysctl -w net.core.somaxconn=4096
        sudo sysctl -w net.ipv4.tcp_max_syn_backlog=4096
        
        # Increase file descriptor limits
        sudo sysctl -w fs.file-max=1000000
        
        # Reduce TIME_WAIT sockets
        sudo sysctl -w net.ipv4.tcp_tw_reuse=1
        
        # Increase local port range
        sudo sysctl -w net.ipv4.ip_local_port_range="10000 65535"
        
        echo "OS tuning complete"

    - name: Install k3s
      shell: bash
      run: |
        echo "=== Installing k3s cluster on pristine VM ==="
        
        # Retry k3s installation up to 3 times
        MAX_RETRIES=3
        for i in $(seq 1 $MAX_RETRIES); do
          echo "Attempt $i/$MAX_RETRIES: Installing k3s..."
          if curl -sfL https://get.k3s.io | sh -s - \
            --write-kubeconfig-mode 644 \
            --disable traefik \
            --disable servicelb \
            --kube-apiserver-arg=max-requests-inflight=400 \
            --kube-apiserver-arg=max-mutating-requests-inflight=200; then
            echo "k3s installation successful"
            break
          else
            echo "k3s installation failed on attempt $i"
            if [ $i -lt $MAX_RETRIES ]; then
              echo "Retrying in 10 seconds..."
              sleep 10
            else
              echo "All installation attempts failed"
              exit 1
            fi
          fi
        done
        
        echo "Waiting for k3s service to start..."
        sleep 15
        
        echo "Waiting for cluster to become ready..."
        retries=0
        while [[ $retries -lt 60 ]]; do
          if sudo k3s kubectl get nodes &>/dev/null; then
            if sudo k3s kubectl wait --for=condition=Ready node --all --timeout=10s 2>/dev/null; then
              echo "k3s cluster ready"
              sudo k3s kubectl get nodes
              exit 0
            fi
          fi
          echo "Waiting for cluster... (attempt $((retries+1))/60)"
          sleep 5
          retries=$((retries + 1))
        done
        echo "ERROR: Cluster failed to become ready within 5 minutes"
        sudo systemctl status k3s || true
        exit 1

    - name: Configure kubectl
      shell: bash
      run: |
        mkdir -p ~/.kube
        sudo cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
        sudo chown $USER:$USER ~/.kube/config
        echo "=== Cluster nodes ==="
        kubectl get nodes
        echo "=== Cluster version ==="
        kubectl version

    - name: Verify cluster
      shell: bash
      run: |
        echo "=== k3s cluster ready ==="
        kubectl get nodes
        
        echo ""
        echo "=== Waiting for API server to stabilize ==="
        sleep 10
        
        echo "=== Verifying API server responsiveness ==="
        kubectl get --raw /readyz
        kubectl get --raw /healthz
